import PDFDocument from "pdfkit";

export const pdfDownload = async (req, res) => {
  try {
    const { result } = req.body;

    if (!result) {
      return res.status(400).json({ message: "Result data is required" });
    }

    const doc = new PDFDocument({ margin: 50 });

    // Correct Headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=notes.pdf"
    );

    doc.pipe(res);

    /* ---------- HEADER ---------- */
    doc
      .fontSize(24)
      .fillColor("#1E3A8A")
      .text("AI Generated Notes", { align: "center" });

    doc.moveDown(1.5);

    /* ---------- MAIN NOTES ---------- */
    if (result.notes) {
      doc
        .fontSize(18)
        .fillColor("black")
        .text("Notes", { underline: true });

      doc.moveDown(0.5);
      doc.fontSize(12).text(result.notes, {
        align: "left",
        lineGap: 4,
      });

      doc.moveDown();
    }

    /* ---------- REVISION POINTS ---------- */
    if (result.revisionPoints?.length > 0) {
      doc
        .fontSize(16)
        .fillColor("#0F766E")
        .text("Quick Revision Points", { underline: true });

      doc.moveDown(0.5);

      result.revisionPoints.forEach((point, i) => {
        doc.fontSize(12).text(`• ${point}`, { indent: 20 });
      });

      doc.moveDown();
    }

    /* ---------- QUESTIONS ---------- */
    if (result.questions) {
      doc
        .fontSize(16)
        .fillColor("#7C3AED")
        .text("Important Questions", { underline: true });

      doc.moveDown(0.5);

      if (result.questions.short?.length > 0) {
        doc.fontSize(14).fillColor("black").text("Short Questions:");
        result.questions.short.forEach((q, i) => {
          doc.fontSize(12).text(`${i + 1}. ${q}`, { indent: 20 });
        });
        doc.moveDown();
      }

      if (result.questions.long?.length > 0) {
        doc.fontSize(14).fillColor("black").text("Long Questions:");
        result.questions.long.forEach((q, i) => {
          doc.fontSize(12).text(`${i + 1}. ${q}`, { indent: 20 });
        });
        doc.moveDown();
      }

      if (result.questions.diagram) {
        doc
          .fontSize(12)
          .text(`Diagram Question: ${result.questions.diagram}`);
        doc.moveDown();
      }
    }

    /* ---------- SUBTOPICS ---------- */
    if (result.subTopics) {
      doc
        .fontSize(16)
        .fillColor("#B45309")
        .text("Subtopics Priority", { underline: true });

      doc.moveDown(0.5);

      Object.entries(result.subTopics).forEach(([priority, topics]) => {
        doc.fontSize(14).fillColor("black").text(`${priority} Priority:`);

        topics.forEach((t) => {
          doc.fontSize(12).text(`• ${t}`, { indent: 20 });
        });

        doc.moveDown(0.5);
      });

      doc.moveDown();
    }

    /* ---------- FOOTER ---------- */
    doc
      .moveDown(2)
      .fontSize(10)
      .fillColor("gray")
      .text("Generated by AI Exam Notes App", { align: "center" });

    doc.end(); // IMPORTANT
  } catch (error) {
    console.error("PDF Error:", error);
    res.status(500).json({ message: "Failed to generate PDF" });
  }
};
